### ISSUE TITLE
Corrigir o json de properties ou acertar o README

### ISSUE THREAD

**Issue by alesilva** [VivaReal/code-challenge#12]
No `README` do desafio, tanto backend quanto frontend, estamos informando que no json de `properties` temos o seguinte layout:
```javascript
{
  "totalProperties": 1, // total number of properties on this json
  "properties": [ // array of properties
    {
      "id": 1, // id :P
      "title": "Imóvel código 1, com 5 quartos e 4 banheiros", // property title
      "price": 1250000, // price
      "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.", // description
      "x": 870, // lat (Spotippos geographic coordinate)
      "y": 867, // long (Spotippos geographic coordinate)
      "beds": 5, // number of beds
      "baths": 4, // number of baths
      "provinces" : ["Scavy"], // spotippos provinces
      "squareMeters": 134
    }
  ]
}
```

Porém no json de carga não temos os atributos `title`, `price` e  `description`.

Precisamos decidir se corrigimos o json de carga ou retiramos esses atributos do desafio.

**Comment by willianribeiro** [comment]
Olá @alesilva, tudo certo?

Eu entrei aqui em busca justamente de esclarecer essa dúvida. 
No [item 3](https://github.com/VivaReal/code-challenge/blob/master/frontend.md#3-ajude-seus-usuários-a-refinar-os-resultados) do Code Challenge de front-end é dito que seria interessante enriquecer a experiência do usuário permitindo-o filtrar os resultados. Um dos filtros é o valor do imóvel, porém no [json disponibilizado](https://github.com/VivaReal/code-challenge/blob/master/properties.json) não existe a propriedade `price`.

Seria o caso de adicionar essa propriedade?

**Comment by stulzer** [comment]
Related #14

**Comment by raulfortes** [comment]
@alesilva foram adicionados os campos ao arquivo properties.json
@willianribeiro o _price_ foi adicionado ao json
